version: "3.8"
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
  # mongodb-:
  #   image: mongo:4.4.6
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb:/data/db

volumes:
  # mongodb:
  #   driver: local
  cache:
    driver: local
